#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LLAMA_DIR="/tmp/llama-cpp-build"
FRAMEWORKS_DIR="$PROJECT_DIR/Frameworks"

echo "=== Building llama.cpp for macOS ARM64 ==="

# Clone if not present
if [ ! -d "$LLAMA_DIR" ]; then
    git clone --depth 1 https://github.com/ggml-org/llama.cpp "$LLAMA_DIR"
fi

cd "$LLAMA_DIR"

# Build with Metal + shared libs
cmake -B build \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DGGML_METAL=ON \
    -DGGML_BLAS=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_BUILD_TYPE=Release

cmake --build build --config Release -j$(sysctl -n hw.ncpu)

# Copy dylibs to Frameworks/
mkdir -p "$FRAMEWORKS_DIR"
cp build/bin/libllama.0.dylib "$FRAMEWORKS_DIR/libllama.0.dylib"
cp build/bin/libggml.0.dylib "$FRAMEWORKS_DIR/libggml.0.dylib"
cp build/bin/libggml-base.0.dylib "$FRAMEWORKS_DIR/libggml-base.0.dylib"
cp build/bin/libggml-cpu.0.dylib "$FRAMEWORKS_DIR/libggml-cpu.0.dylib"
cp build/bin/libggml-metal.0.dylib "$FRAMEWORKS_DIR/libggml-metal.0.dylib"
cp build/bin/libggml-blas.0.dylib "$FRAMEWORKS_DIR/libggml-blas.0.dylib"

# Copy Metal shader (location varies by llama.cpp version)
cp build/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal "$FRAMEWORKS_DIR/ggml-metal.metal" 2>/dev/null || \
    cp build/bin/ggml-metal.metal "$FRAMEWORKS_DIR/" 2>/dev/null || true
cp build/bin/default.metallib "$FRAMEWORKS_DIR/" 2>/dev/null || true

# Copy headers needed for bridging
mkdir -p "$FRAMEWORKS_DIR/include"
cp "$LLAMA_DIR/include/llama.h" "$FRAMEWORKS_DIR/include/"
cp "$LLAMA_DIR/ggml/include/ggml.h" "$FRAMEWORKS_DIR/include/"
cp "$LLAMA_DIR/ggml/include/ggml-backend.h" "$FRAMEWORKS_DIR/include/"
cp "$LLAMA_DIR/ggml/include/ggml-alloc.h" "$FRAMEWORKS_DIR/include/"
cp "$LLAMA_DIR/ggml/include/ggml-metal.h" "$FRAMEWORKS_DIR/include/" 2>/dev/null || true

# Fix install names to use @rpath
cd "$FRAMEWORKS_DIR"
for dylib in *.dylib; do
    install_name_tool -id "@rpath/$dylib" "$dylib"
done

# Fix cross-references between dylibs
for dylib in *.dylib; do
    for dep in *.dylib; do
        old_path=$(otool -L "$dylib" | grep "$dep" | grep -v "@rpath" | awk '{print $1}' || true)
        if [ -n "$old_path" ] && [ "$old_path" != "$dylib" ]; then
            install_name_tool -change "$old_path" "@rpath/$dep" "$dylib"
        fi
    done
done

echo "=== Done. Dylibs in $FRAMEWORKS_DIR ==="
ls -la "$FRAMEWORKS_DIR"/*.dylib
